### ISSUE TITLE
Communicate a minimum feature set

### ISSUE THREAD

**Issue by rainerschoe** [IBM/appconfiguration-rust-sdk#8]
Planned features:
- [x] Get single feature - #13 
- [x] Get all features - #13 
- [x] Evaluate a feature - #13 
- [x] Get single property - #13
- [x] Get all properties - #13 
- [x] Evaluate a property - #13
- [x] Proxied features - #26
- [x] Proxied properties - #28 

Not planned ([`v0..x.y` milestone](https://github.ibm.com/salva/appconfiguration-rust-sdk/milestone/1))
 * Get secret property
 * Evaluate a secret property
 * Send custom metrics
 * Set listener for feature and property data changes (callback)
 * Admin interface
 * Token renewal / authenticator (#3)

Never planned, not a feature:
 * Singleton (not a library feature)
 * Context switch (1:1 client context relationship)

**Comment by rainerschoe** [comment]
Sending metrics back on feature evaluation is important for billing, but can be implemented after january
